apiVersion: v1
kind: Service
metadata:
  name: office-service
  namespace: default
spec:
  selector:
    app: office-ms
  ports:
    - port: 2024
      targetPort: 2024
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: office-ms-cluster
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: office-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: office-ms
    spec:
      containers:
      - name: office-ms
        image: docker.io/anh3h/fineract-cn-office:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: eureka.instance.hostname
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: eureka-ip
          - name: ribbon.listOfServers
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: ribbon-config
          - name: eureka.client.serviceUrl.defaultZone
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: eureka-default
          - name: activemq.brokerUrl
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: activemq-ip
          - name: cassandra.contactPoints
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: cassandra-ip
          - name: mariadb.host
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: mariadb-ip
          - name: system.publicKey.timestamp
            valueFrom:
              configMapKeyRef:
                key: TIMESTAMP
                name: secret-config
          - name: system.publicKey.modulus
            valueFrom:
              configMapKeyRef:
                key: MODULUS
                name: secret-config
          - name: system.publicKey.exponent
            valueFrom:
              configMapKeyRef:
                key: EXPONENT
                name: secret-config
        ports:
          - containerPort: 2024
