apiVersion: v1
kind: Service
metadata:
  name: provisioner-service
  namespace: default
spec:
  selector:
    app: provisioner-ms
  ports:
    - port: 2020
      targetPort: 2020
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: provisioner-ms-cluster
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provisioner-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: provisioner-ms
    spec:
      containers:
      - name: provisioner-ms
        image: docker.io/anh3h/fineract-cn-provisioner:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: eureka.instance.hostname
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: eureka-ip
          - name: ribbon.listOfServers
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: ribbon-config
          - name: eureka.client.serviceUrl.defaultZone
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: eureka-default
          - name: activemq.brokerUrl
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: activemq-ip
          - name: cassandra.contactPoints
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: cassandra-ip
          - name: mariadb.host
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: mariadb-ip
        ports:
          - containerPort: 2020
